-- Your SQL goes here
CREATE TABLE users (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  username VARCHAR(24) NOT NULL UNIQUE,
  email VARCHAR(48) NOT NULL UNIQUE,
  salt VARCHAR(4) NULL,
  password VARCHAR(128) NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  date_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
